run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused

linters-settings:
  goimports:
    local-prefixes: github.com/digitalocean/karpenter-provider-digitalocean
  gosec:
    excludes:
      - G101  # false positives for hardcoded credentials
  govet:
    enable-all: true
    disable:
      - fieldalignment

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - unparam
    - path: fake/
      linters:
        - gosec
        - unparam
    - path: zz_generated
      linters:
        - all
