{{- if and (not .Values.digitalocean.existingSecret) .Values.digitalocean.accessToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "karpenter-do.fullname" . }}-do-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter-do.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.digitalocean.secretKey }}: {{ .Values.digitalocean.accessToken | b64enc | quote }}
{{- end }}
